Phone book
EasyCode-JavaScriptReact-v1/javascript-react-course-reses90 pull request #35
Opened 2018-07-29 17:58 UTC by Balashov-nikita

2018-07-31 09:21 UTC, OlegLustenko requested changes

2018-07-31 13:34 UTC, Balashov-nikita commented on phone-book/src/modules/keypad.js
> +            const buttonForKeypad = createElem('div');
by hand(((

2018-07-31 13:37 UTC, Balashov-nikita commented on phone-book/src/modules/helper.js
> +        Element.prototype.removeClass = function(className) {
why not?

2018-07-31 18:44 UTC, OlegLustenko requested changes

2018-07-31 18:44 UTC, OlegLustenko commented on phone-book/src/modules/call-mode.js
> +    createElem
I don't see usage of createElem

2018-07-31 18:44 UTC, OlegLustenko commented on phone-book/src/modules/contact.js
> +                const userInfo = {
you don't have to acces to real DOM, please sort your virtual-data

2018-07-31 18:44 UTC, OlegLustenko commented on phone-book/src/modules/contact.js
> +        arrayWithUsers.forEach(user => {
```js
return `
 <tbody>
  ${this.renderUsers()}
</tbody>
`
```

2018-07-31 18:50 UTC, OlegLustenko commented on phone-book/src/index.js
> +    constructor() {}
please add a state to App.

2018-08-03 09:24 UTC, OlegLustenko submitted a review, later dismissed

2018-08-20 17:08 UTC, closed without merging